name: Update Telegram Ads Stats

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browser
        run: npx playwright install --with-deps chromium

      - name: Update Telegram statistics
        env:
          SUPABASE_URL: "https://oxclimxygexnezblrhpz.supabase.co"
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: node update-stats.js
